import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import GlobalDialog from "./GlobalDialog";
import Header from "./Header";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <GlobalDialog />
        <Toaster/>
        <div className="max-w-full w-dvw bg-mainDarkBg text-mainWhite">
          <Header/>
          <div className="max-w-[1300px] mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
