import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import GlobalDialog from "./GlobalDialog";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <GlobalDialog />
        <div className="max-w-full w-dvw bg-black text-mainWhite">
          <div className="max-w-[1440px] mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
